name: CI Laravel Backend

on:
  push:
    branches: [ main, dev, staging ]
  pull_request:
    branches: [ main, dev, staging ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Copy .env
        run: |
          if [ ! -f .env ]; then
            cp .env.example .env
          fi

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate app key
        run: php artisan key:generate

      - name: Directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run unit tests
        run: php artisan test
